name         'fernandoalmeida-nginx'
version      '0.0.1'
source       'https://github.com/fernandoalmeida/puppet-nginx.git'
author       'Fernando Almeida'
license      'Apache License, Version 2.0'
summary      'A Puppet module for installing and configuring Nginx'
description  'A Puppet module for installing and configuring Nginx'
project_page 'https://github.com/fernandoalmeida/puppet-nginx'
